# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-23 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.IntegerField(max_length=8, unique=True)),
                ('po_date', models.DateField()),
                ('company', models.CharField(default='optiPulse, Inc.', max_length=60)),
                ('company_address', models.CharField(default='1008 Coal Ave SE, Ste. 120', max_length=60)),
                ('company_city', models.CharField(default='Albuquerque', max_length=60)),
                ('company_state', models.CharField(default='New Mexico', max_length=60)),
                ('company_zipcode', models.CharField(default='87106', max_length=16)),
                ('company_phone', models.CharField(default='888.978.4943', max_length=24)),
                ('purchased_from_first_name', models.CharField(blank=True, max_length=80, null=True)),
                ('purchased_from_last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('purchased_from_phone', models.CharField(blank=True, max_length=24, null=True)),
                ('purchased_from_fax', models.CharField(blank=True, max_length=24, null=True)),
                ('purchased_from_email', models.EmailField(blank=True, max_length=80, null=True)),
                ('purchased_from_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('purchased_from_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('purchased_from_city', models.CharField(blank=True, max_length=80, null=True)),
                ('purchased_from_state', models.CharField(blank=True, max_length=80, null=True)),
                ('purchased_from_zip', models.CharField(blank=True, max_length=80, null=True)),
                ('purchased_from_country', models.CharField(blank=True, max_length=80, null=True)),
                ('bill_to_company', models.CharField(blank=True, max_length=60, null=True)),
                ('bill_to_first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('bill_to_last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('bill_to_email', models.CharField(blank=True, max_length=80, null=True)),
                ('bill_to_phone', models.CharField(blank=True, max_length=24, null=True)),
                ('bill_to_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('bill_to_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('approved_by_doe', models.BooleanField(default=False)),
                ('date_approved_by_doe', models.DateField(blank=True, default='', null=True)),
                ('approved_by_ceo', models.BooleanField(default=False)),
                ('date_approved_by_ceo', models.DateField(blank=True, default='', null=True)),
                ('po_document', models.FileField(blank=True, null=True, upload_to='')),
                ('po_document_location', models.CharField(blank=True, max_length=255, null=True)),
                ('terms', models.CharField(choices=[('CC', 'Credit Card'), ('30', 'Net 30')], default='CC', max_length=2)),
                ('fob', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('shipping', models.CharField(choices=[('FE', 'optiPulse FedEX Account'), ('VE', 'Paid by Vendor'), ('EX', 'Additional Charge')], default='FE', max_length=2)),
                ('sales_tax', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchased_from_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Contact')),
            ],
            options={
                'ordering': ['po_number'],
            },
        ),
    ]
