# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-16 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchased_from_company',
        ),
    ]
