# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-23 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.IntegerField(unique=True),
        ),
    ]
