# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-23 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_auto_20180723_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='company',
            field=models.CharField(blank=True, default='optiPulse, Inc.', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='company_address',
            field=models.CharField(blank=True, default='1008 Coal Ave SE, Ste. 120', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='company_city',
            field=models.CharField(blank=True, default='Albuquerque', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='company_phone',
            field=models.CharField(blank=True, default='888.978.4943', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='company_state',
            field=models.CharField(blank=True, default='New Mexico', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='company_zipcode',
            field=models.CharField(blank=True, default='87106', max_length=16, null=True),
        ),
    ]
