# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-04 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_auto_20180803_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.Invoice'),
        ),
    ]
