# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-16 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0026_auto_20180711_1003'),
        ('financial', '0002_remove_purchaseorder_purchased_from_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchased_from_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Contact'),
            preserve_default=False,
        ),
    ]
