# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-16 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_purchaseorder_purchased_from_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchased_from_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Contact', to_field='company'),
        ),
    ]
