# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-23 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20180723_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='company_address',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_to_city',
            field=models.CharField(blank=True, default='Albuquerque', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_to_state',
            field=models.CharField(blank=True, default='New Mexico', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_to_zipcode',
            field=models.CharField(blank=True, default='87102', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company_address1',
            field=models.CharField(blank=True, default='1008 Coal Ave SE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company_address2',
            field=models.CharField(blank=True, default='Ste. 120', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_address1',
            field=models.CharField(blank=True, default='1008 Coal Ave. SE', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_address2',
            field=models.CharField(blank=True, default='Ste. 120', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_city',
            field=models.CharField(blank=True, default='Albuquerque', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_company',
            field=models.CharField(blank=True, default='optiPulse, Inc.', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_email',
            field=models.CharField(blank=True, default='info@optipulse.com', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_first_name',
            field=models.CharField(blank=True, default='Eric', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_last_name',
            field=models.CharField(blank=True, default='Gieryng', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_phone',
            field=models.CharField(blank=True, default='888.978.4943 x704', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_state',
            field=models.CharField(blank=True, default='New Mexico', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_zipcode',
            field=models.CharField(blank=True, default='87106', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill_to_address1',
            field=models.CharField(blank=True, default='101 Broadway Blvd', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill_to_address2',
            field=models.CharField(blank=True, default='Ste. 1100', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill_to_company',
            field=models.CharField(blank=True, default='optiPulse, Inc.', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill_to_email',
            field=models.CharField(blank=True, default='billing@optipulse.com', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill_to_first_name',
            field=models.CharField(blank=True, default='Caitlin', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill_to_last_name',
            field=models.CharField(blank=True, default='Marchi', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill_to_phone',
            field=models.CharField(blank=True, default='888.978.4943 x706', max_length=24, null=True),
        ),
    ]
