# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-04 03:16
from __future__ import unicode_literals

import business_management.financial.models.purchase_orders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_auto_20180803_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.IntegerField(default=business_management.financial.models.purchase_orders.get_po_number, unique=True),
        ),
    ]
