# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-26 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prof_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/avatars/'),
        ),
    ]
