# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171214_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='digital_sig',
            field=models.ImageField(blank=True, null=True, upload_to='business_management/static/images/users/signatures'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='prof_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_management/static/images/users/avatars'),
        ),
    ]
