# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171216_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prof_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
