# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_asset_ui', models.CharField(max_length=60, unique=True)),
                ('asset_tag', models.CharField(max_length=60, unique=True)),
                ('serial_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True)),
                ('purchased_from', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('inactive_date', models.DateField(null=True)),
                ('asset_type', models.CharField(choices=[('CE', 'Computer Equipment'), ('LE', 'Lab Equipment'), ('FU', 'Furniture'), ('SO', 'Software')], default='CE', max_length=2)),
                ('location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['purchase_date'],
            },
        ),
    ]
