# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedasset',
            name='fixed_asset_ui',
        ),
    ]
