# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_clockpunch_hours_for_the_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockpunch',
            name='punch_in_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clockpunch',
            name='punch_out_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clockpunch',
            name='punched_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clockpunch',
            name='punched_out',
            field=models.BooleanField(default=False),
        ),
    ]
