# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_fixedasset_fixed_asset_ui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='inactive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
