# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20180226_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='model_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='purchase_condition',
            field=models.CharField(choices=[('NE', 'New'), ('US', 'Used'), ('MR', 'Manufacturer Refurbished'), ('RE', 'Refurbished')], default='NE', max_length=2),
        ),
    ]
