# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20180815_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockpunch',
            name='employee',
        ),
        migrations.DeleteModel(
            name='ClockPunch',
        ),
    ]
