# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20180227_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='manufacturer',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='model_number',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
