# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-26 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20180826_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='project',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
