# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20180227_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_type',
            field=models.CharField(choices=[('CE', 'Computer Equipment'), ('OE', 'Office Equipment'), ('LE', 'Lab Equipment'), ('FU', 'Furniture'), ('SO', 'Software')], default='CE', max_length=2),
        ),
    ]
