# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20180227_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_tag',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='manufacturer',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='model_number',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='purchased_from',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
