# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_fixedasset_description'),
    ]
