# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20180227_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
