# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20180227_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
