# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0011_auto_20180228_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesheet_ui', models.CharField(max_length=60, unique=True)),
                ('week_start', models.DateField()),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('employee_signature', models.BooleanField(default=False)),
                ('employee_sign_date', models.DateField()),
                ('supervisor_signature', models.BooleanField(default=False)),
                ('supervisor_sign_date', models.DateField()),
                ('supervisor_comments', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_start'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('day_of_week', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timesheet_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Timesheet')),
            ],
            options={
                'ordering': ['row_num'],
            },
        ),
    ]
