# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_timesheet_timesheetrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='employee_sign_date',
            field=models.DateField(blank=True),
        ),
    ]
