# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_auto_20180516_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='employee_sign_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='supervisor_sign_date',
            field=models.DateField(null=True),
        ),
    ]
