# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_auto_20180516_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='employee_signature',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='supervisor_signature',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
