# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-10 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='address2',
        ),
        migrations.AddField(
            model_name='contact',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
