# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_auto_20180710_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('VE', 'Vendor'), ('CO', 'Contractor'), ('PC', 'Potential Customer'), ('PI', 'Potential Investor'), ('CU', 'Customer'), ('IN', 'Investor'), ('PA', 'Partner'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
