# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_auto_20180711_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
    ]
