# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_auto_20180711_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
