# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_contact_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
