# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_auto_20180711_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=60),
        ),
    ]
