# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0025_auto_20180711_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=60),
        ),
    ]
