# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-26 13:05
from __future__ import unicode_literals

import business_management.engineering.models.gaas_wafer_designs
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlipChip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(max_length=255)),
                ('bond_pressure', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('bond_heat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bond_time', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('bond_date', models.DateTimeField()),
                ('bond_tool', models.CharField(default='', max_length=255)),
                ('carrier', models.CharField(default='', max_length=255)),
                ('geo_location', models.CharField(default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_trash', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['serial_num'],
            },
        ),
        migrations.CreateModel(
            name='GaasWafer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wafer_ui', models.CharField(max_length=60, unique=True)),
                ('growth_date', models.DateTimeField()),
                ('wafer_position', models.CharField(default='', max_length=255)),
                ('reflectance_map', models.CharField(default='', max_length=255)),
                ('wafer_diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('conductivity', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('vendor', models.CharField(default='', max_length=255)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('wafer_growth_lot', models.CharField(default='', max_length=255)),
                ('wavelength', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('gain_offset', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('designed_operating_temp', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_trash', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['wafer_ui'],
            },
        ),
        migrations.CreateModel(
            name='GaasWaferDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_ui', models.CharField(max_length=60, unique=True)),
                ('emitting', models.CharField(choices=[('TE', 'Top-Emitting'), ('BE', 'Bottom-Emitting')], default='TE', max_length=2)),
                ('contact_location', models.CharField(default='', max_length=255)),
                ('optical_power', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('design_date', models.DateTimeField()),
                ('designer', models.CharField(default='', max_length=255)),
                ('designer_ui', models.CharField(blank=True, default='', max_length=255)),
                ('design_document', models.FileField(blank=True, upload_to=business_management.engineering.models.gaas_wafer_designs.upload_path)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_trash', models.BooleanField(default=False)),
                ('inactive_date', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['design_ui'],
            },
        ),
        migrations.CreateModel(
            name='LaserMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laser_mask_ui', models.CharField(max_length=60, unique=True)),
                ('mask_layer', models.CharField(default='', max_length=255)),
                ('fab_date', models.DateTimeField()),
                ('fab_vendor', models.CharField(default='', max_length=255)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_trash', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['laser_mask_ui'],
            },
        ),
        migrations.CreateModel(
            name='LaserMaskDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laser_mask_design_ui', models.CharField(max_length=60, unique=True)),
                ('mask_layers', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('design_date', models.DateTimeField(blank=True, null=True)),
                ('designer', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pcm', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('critical_dimensions', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('dimensions', models.CharField(default='', max_length=255)),
                ('thickness', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('material', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('number_of_products', models.IntegerField(blank=True, default=0, null=True)),
                ('chip_list', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('design_document', models.FileField(blank=True, null=True, upload_to='')),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_trash', models.BooleanField(default=False)),
                ('inactive_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['laser_mask_design_ui'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_trash', models.BooleanField(default=False)),
                ('serial_num', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('build_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['serial_num'],
            },
        ),
        migrations.AddField(
            model_name='lasermask',
            name='mask_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.LaserMaskDesign'),
        ),
        migrations.AddField(
            model_name='gaaswafer',
            name='wafer_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.GaasWaferDesign'),
        ),
    ]
