# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlipChip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_trash', models.BooleanField(default=False)),
                ('serial_num', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('bond_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['serial_num'],
            },
        ),
    ]
