# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_flipchip_bond_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipchip',
            name='bond_heat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flipchip',
            name='bond_time',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flipchip',
            name='bond_tool',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flipchip',
            name='carrier',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flipchip',
            name='geo_location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
