# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0004_auto_20171209_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaasWaferDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_ui', models.CharField(max_length=255)),
                ('emitting', models.CharField(choices=[('TE', 'Top-Emitting'), ('BE', 'Bottom-Emitting')], default='TE', max_length=2)),
                ('contact_location', models.CharField(default='', max_length=255)),
                ('optical_power', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('design_date', models.DateTimeField()),
                ('designer', models.CharField(default='', max_length=255)),
                ('designer_ui', models.CharField(default='', max_length=255)),
                ('design_document', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_trash', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['design_ui'],
            },
        ),
    ]
