# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0005_gaaswaferdesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaasWafer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wafer_ui', models.CharField(max_length=60, unique=True)),
                ('growth_date', models.DateTimeField()),
                ('wafer_position', models.CharField(default='', max_length=255)),
                ('reflectance_map', models.CharField(default='', max_length=255)),
                ('wafer_diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('conductivity', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('vendor', models.CharField(default='', max_length=255)),
                ('wafer_growth_lot', models.CharField(default='', max_length=255)),
                ('wavelength', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('gain_offset', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('designed_operating_temp', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_trash', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['wafer_ui'],
            },
        ),
        migrations.AlterField(
            model_name='gaaswaferdesign',
            name='design_ui',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='gaaswafer',
            name='wafer_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.GaasWaferDesign'),
        ),
    ]
