# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0006_auto_20171210_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaaswaferdesign',
            name='design_ui',
            field=models.CharField(max_length=60),
        ),
    ]
