# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0008_auto_20171210_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserMaskDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laser_mask_design_ui', models.CharField(max_length=60, unique=True)),
                ('mask_layers', models.CharField(default='', max_length=255)),
                ('design_date', models.DateTimeField()),
                ('designer', models.CharField(default='', max_length=255)),
                ('pcm', models.CharField(default='', max_length=255)),
                ('critical_dimensions', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('dimensions', models.CharField(default='', max_length=255)),
                ('thickness', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('material', models.CharField(default='', max_length=255)),
                ('number_of_products', models.IntegerField(default=0)),
                ('chip_list', models.CharField(default='', max_length=255)),
                ('design_document', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_trash', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['laser_mask_design_ui'],
            },
        ),
    ]
