# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0009_lasermaskdesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laser_mask_ui', models.CharField(max_length=60, unique=True)),
                ('mask_layer', models.CharField(default='', max_length=255)),
                ('fab_date', models.DateTimeField()),
                ('fab_vendor', models.CharField(default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_trash', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mask_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.LaserMaskDesign')),
            ],
            options={
                'ordering': ['laser_mask_ui'],
            },
        ),
    ]
