# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0010_lasermask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasermaskdesign',
            name='design_document',
            field=models.FileField(upload_to=''),
        ),
    ]
