# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0012_auto_20171220_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lasermaskdesign',
            name='design_document',
        ),
    ]
