# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0014_lasermaskdesign_design_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasermaskdesign',
            name='design_document',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
