# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0015_auto_20171220_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasermaskdesign',
            name='design_document',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
