# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0011_auto_20171220_1022'),
        ('engineering', '0017_auto_20171220_1151'),
    ]

    operations = [
    ]
