# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0019_auto_20171220_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasermaskdesign',
            name='chip_list',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lasermaskdesign',
            name='critical_dimensions',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='lasermaskdesign',
            name='design_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lasermaskdesign',
            name='designer',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lasermaskdesign',
            name='mask_layers',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lasermaskdesign',
            name='material',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lasermaskdesign',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lasermaskdesign',
            name='number_of_products',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lasermaskdesign',
            name='pcm',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lasermaskdesign',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
    ]
