# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0020_auto_20171221_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaaswaferdesign',
            name='inactive_date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
