# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0021_gaaswaferdesign_inactive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaaswaferdesign',
            name='inactive_date',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
