# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0023_auto_20180430_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasermaskdesign',
            name='inactive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
