# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0024_lasermaskdesign_inactive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaaswafer',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
