# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 19:58
from __future__ import unicode_literals

import business_management.engineering.models.gaas_wafer_designs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0025_gaaswafer_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasermask',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gaaswaferdesign',
            name='design_document',
            field=models.FileField(blank=True, upload_to=business_management.engineering.models.gaas_wafer_designs.upload_path),
        ),
    ]
