# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-09 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0026_auto_20180515_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaaswaferdesign',
            name='designer_ui',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
